### ISSUE TITLE
Message broadcast multiple times

### ISSUE THREAD

**Issue by itrogers** [thinkalpha/socket.io-amqp0#1]
Hey there, thanks for the great library. I've experimented with this for a while and ran into an issue that I wanted to bring to your attention.

I've noticed an issue where a message will be broadcast N times the amount of sockets in any given room. Example, if 3 users are connected to "room1" - then each of the 3 users will received the emitted event 3 times. If 5 users, 5 times, etc.

Let me know any additional information needed and how I might be able to help resolve the issue.

**Comment by bytenik** [comment]
Apparently, I didn't have notifications turned on for issues here. Are you still working with this library and are you still having this issue with the latest version?

**Comment by itrogers** [comment]
@bytenik I am not using this library at the moment. As such I have not been able to test with the latest version.

**Comment by bytenik** [comment]
Okay, I'm going to close this then. If it turns out to be an issue for someone else, I can always reopen. I haven't witnessed this in our production use.
